<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <BeatSaberDir>D:\BSManager\BSInstances\1.45.1</BeatSaberDir>
        <ImportBSMTTargets>true</ImportBSMTTargets>
        <BSMTProjectType>BSIPA</BSMTProjectType>
        <GameDirectory>D:\BSManager\BSInstances\1.45.1</GameDirectory>
        <GenerateManifest>true</GenerateManifest>
        <PluginId>SiraUtil</PluginId>
        <PluginName>SiraUtil</PluginName>
        <CopyPDB>false</CopyPDB>
        <DisableCopyToGame>false</DisableCopyToGame>
        <TargetFramework>net472</TargetFramework>
        <OutputType>Library</OutputType>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <Copyright>Copyright © Auros 2021-2025</Copyright>
        <AssemblyName>SiraUtil</AssemblyName>
        <RootNamespace>SiraUtil</RootNamespace>
        <EnableFrameworkPathOverride>true</EnableFrameworkPathOverride>
        <FrameworkPathOverride>$(BeatSaberDir)\Beat Saber_Data\Managed</FrameworkPathOverride>
        <ReferencePath>$(BeatSaberDir)\Beat Saber_Data\Managed;$(BeatSaberDir)\Libs;$(BeatSaberDir)\Plugins;$(ReferencePath)</ReferencePath>
        <AssemblySearchPaths>$(ReferencePath);$(AssemblySearchPaths)</AssemblySearchPaths>
    </PropertyGroup>

    <PropertyGroup Condition="'$(CI)' != ''">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>SiraUtil</PackageId>
        <Title>SiraUtil</Title>
        <Authors>Auros</Authors>
        <Version>3.4.0</Version>
        <Description>A powerful utility mod which provides more tools to Beat Saber modders.</Description>
        <GameVersion>1.45.1</GameVersion>
        <Icon>SiraUtil.Resources.logo.png</Icon>
    </PropertyGroup>

    <ItemGroup>
        <DependsOn Include="BSIPA" Version="^4.3.6" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Sabers\Effects\SaberBurnMarkAreaLatch.cs" />
        <Compile Remove="Sabers\Effects\SaberBurnMarkAreaPatch.cs" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="0Harmony" />
        <Reference Remove="System.Net.Http" />
        <Reference Include="BeatSaber.Init" />
        <Reference Include="BeatSaber.Multiplayer.Core" />
        <Reference Include="BeatSaber.ViewSystem" Publicize="True" />
        <Reference Include="$(BeatSaberDir)\Beat Saber_Data\Managed\BGLib.AppFlow.dll" Publicize="True">
            <Private>False</Private>
        </Reference>
        <Reference Include="BGLib.DotnetExtension" />
        <Reference Include="BGLib.UnityExtension" />
        <Reference Include="BGNetCore" />
        <Reference Include="Core" />
        <Reference Include="DataModels" />
        <Reference Include="GameInit" />
        <Reference Include="GameplayCore" />
        <Reference Include="Hive.Versioning" />
        <Reference Include="HMRendering" />
        <Reference Include="Mono.Cecil" />
        <Reference Include="netstandard" />
        <Reference Include="Newtonsoft.Json" />
        <Reference Include="BGLib.Polyglot" />
        <Reference Include="Rendering" />
        <Reference Include="SaberTrail" Publicize="True" />
        <Reference Include="Unity.InputSystem" />
        <Reference Include="Unity.TextMeshPro" />
        <Reference Include="Unity.XR.Management" />
        <Reference Include="Unity.XR.OpenXR" />
        <Reference Include="UnityEngine" />
        <Reference Include="UnityEngine.AnimationModule" />
        <Reference Include="UnityEngine.AudioModule" />
        <Reference Include="UnityEngine.CoreModule" />
        <Reference Include="UnityEngine.InputLegacyModule" />
        <Reference Include="UnityEngine.ParticleSystemModule" />
        <Reference Include="UnityEngine.SpatialTracking" Publicize="True" />
        <Reference Include="UnityEngine.SubsystemsModule" />
        <Reference Include="UnityEngine.UI" />
        <Reference Include="UnityEngine.UIElementsModule" />
        <Reference Include="UnityEngine.UIModule" />
        <Reference Include="UnityEngine.UnityWebRequestModule" />
        <Reference Include="UnityEngine.UnityWebRequestWWWModule" />
        <Reference Include="UnityEngine.VRModule" />
        <Reference Include="$(BeatSaberDir)\Beat Saber_Data\Managed\Main.dll" Publicize="True">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(BeatSaberDir)\Beat Saber_Data\Managed\HMLib.dll" Publicize="True">
            <Private>False</Private>
        </Reference>
        <Reference Include="HMUI" />
        <Reference Include="IPA.Loader" />
        <Reference Include="UnityEngine.XRModule" />
        <Reference Include="$(BeatSaberDir)\Beat Saber_Data\Managed\VRUI.dll" Publicize="True">
            <Private>False</Private>
        </Reference>
        <Reference Include="$(BeatSaberDir)\Beat Saber_Data\Managed\Zenject.dll" Publicize="True">
            <Private>False</Private>
        </Reference>
        <Reference Include="Zenject-usage" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\logo.png" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Unity.Analyzers" Version="1.26.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="BeatSaberModdingTools.Tasks" Version="2.0.0-beta7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>build; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
